import type { AppTheme } from "./index";

export const defaultTheme: AppTheme = {
  id: "default",
  name: "Default",
  light: {
    bg: "#ffffff",
    bgSecondary: "#f6f8fa",
    fg: "#1f2328",
    muted: "#656d76",
    border: "#d0d7de",
    accent: "#1a73e8",
    accentFg: "#ffffff",
    errorBg: "#fff5f5",
    errorBorder: "#f5c2c7",
    errorFg: "#b42318",
    h1: "inherit",
    h2: "inherit",
    h3: "inherit",
    h4: "inherit",
    h5: "inherit",
    h6: "inherit",
    codeBg: "rgba(127, 127, 127, 0.12)",
    codeFg: "inherit",
    inlineCodeFg: "inherit",
    blockquoteBg: "transparent",
    selection: "#b3d7ff80",
  },
  dark: {
    bg: "#0d1117",
    bgSecondary: "#161b22",
    fg: "#e6edf3",
    muted: "#8b949e",
    border: "#30363d",
    accent: "#4493f8",
    accentFg: "#ffffff",
    errorBg: "#2d1618",
    errorBorder: "#5c2b2f",
    errorFg: "#ff7b72",
    h1: "inherit",
    h2: "inherit",
    h3: "inherit",
    h4: "inherit",
    h5: "inherit",
    h6: "inherit",
    codeBg: "rgba(127, 127, 127, 0.15)",
    codeFg: "inherit",
    inlineCodeFg: "inherit",
    blockquoteBg: "transparent",
    selection: "#1f6feb66",
  },
};
